# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Connection do
  @moduledoc """
  Handle Tesla connections for AnchoreEngineAPIServer.
  """

  use Tesla

  # Add any middleware here (authentication)
  plug Tesla.Middleware.Headers, [{"User-Agent", "Elixir"}]
  plug Tesla.Middleware.JSON

  @doc """
  Configure an authless client connection

  # Returns

  Tesla.Env.client
  """
  @spec new() :: Tesla.Env.client
  def new do
    Tesla.client([])
  end

  def new(url, user, pwd) do
    middleware = [
      {Tesla.Middleware.BaseUrl, url},
      Tesla.Middleware.JSON,
      {Tesla.Middleware.Headers, [{"authorization", "Basic " <> Base.encode64("#{user}:#{pwd}")}]}
    ]

    Tesla.client(middleware)
  end
end
