# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.Account do
  @moduledoc """
  Account information
  """

  @derive [Poison.Encoder]
  defstruct [
    :created_at,
    :email,
    :last_updated,
    :name,
    :state,
    :type
  ]

  @type t :: %__MODULE__{
    :created_at => DateTime.t,
    :email => String.t,
    :last_updated => DateTime.t,
    :name => String.t,
    :state => String.t,
    :type => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.Account do
  def decode(value, _options) do
    value
  end
end

