# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.AccountStatus do
  @moduledoc """
  A summary of account status
  """

  @derive [Poison.Encoder]
  defstruct [
    :state
  ]

  @type t :: %__MODULE__{
    :state => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.AccountStatus do
  def decode(value, _options) do
    value
  end
end

