# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.AccountCreationRequest do
  @moduledoc """
  An account to create/add to the system. If already exists will return 400.
  """

  @derive [Poison.Encoder]
  defstruct [
    :email,
    :name
  ]

  @type t :: %__MODULE__{
    :email => String.t,
    :name => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.AccountCreationRequest do
  def decode(value, _options) do
    value
  end
end

