# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.AnalysisArchiveRulesSummary do
  @moduledoc """
  Summary of the transition rule set
  """

  @derive [Poison.Encoder]
  defstruct [
    :count,
    :last_updated
  ]

  @type t :: %__MODULE__{
    :count => integer(),
    :last_updated => DateTime.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.AnalysisArchiveRulesSummary do
  def decode(value, _options) do
    value
  end
end

