# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.AnalysisArchiveTransitionRule do
  @moduledoc """
  A rule for auto-archiving image analysis by time and/or tag-history
  """

  @derive [Poison.Encoder]
  defstruct [
    :analysis_age_days,
    :created_at,
    :last_updated,
    :selector,
    :system_global,
    :tag_versions_newer,
    :transition
  ]

  @type t :: %__MODULE__{
    :analysis_age_days => integer(),
    :created_at => DateTime.t,
    :last_updated => DateTime.t,
    :selector => ImageSelector,
    :system_global => boolean(),
    :tag_versions_newer => integer(),
    :transition => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.AnalysisArchiveTransitionRule do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:selector, :struct, AnchoreEngineAPIServer.Model.ImageSelector, options)
  end
end

