# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.AnalysisArchiveTransitionHistory do
  @moduledoc """
  A rule for auto-archiving image analysis by time and/or tag-history
  """

  @derive [Poison.Encoder]
  defstruct [
    :created_at,
    :imageDigest,
    :last_updated,
    :rule_id,
    :transition,
    :transition_task_id
  ]

  @type t :: %__MODULE__{
    :created_at => DateTime.t,
    :imageDigest => String.t,
    :last_updated => DateTime.t,
    :rule_id => String.t,
    :transition => String.t,
    :transition_task_id => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.AnalysisArchiveTransitionHistory do
  def decode(value, _options) do
    value
  end
end

