# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.AnalysisArchiveSummary do
  @moduledoc """
  A summarization of the analysis archive, including size, counts, etc. This archive stores image analysis only, never the actual image content or layers.
  """

  @derive [Poison.Encoder]
  defstruct [
    :last_updated,
    :total_data_bytes,
    :total_image_count,
    :total_tag_count
  ]

  @type t :: %__MODULE__{
    :last_updated => DateTime.t,
    :total_data_bytes => integer(),
    :total_image_count => integer(),
    :total_tag_count => integer()
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.AnalysisArchiveSummary do
  def decode(value, _options) do
    value
  end
end

