# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.AnchoreErrorCode do
  @moduledoc """
  A description of an anchore error code (name, description)
  """

  @derive [Poison.Encoder]
  defstruct [
    :description,
    :name
  ]

  @type t :: %__MODULE__{
    :description => String.t,
    :name => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.AnchoreErrorCode do
  def decode(value, _options) do
    value
  end
end

