# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.AnchoreImage do
  @moduledoc """
  A unique image in the engine. May have multiple tags or references. Unique to an image content across registries or repositories.
  """

  @derive [Poison.Encoder]
  defstruct [
    :analysis_status,
    :annotations,
    :created_at,
    :imageDigest,
    :image_content,
    :image_detail,
    :image_status,
    :last_updated,
    :userId
  ]

  @type t :: %__MODULE__{
    :analysis_status => String.t,
    :annotations => Object,
    :created_at => DateTime.t,
    :imageDigest => String.t,
    :image_content => ImageContent,
    :image_detail => [ImageDetail],
    :image_status => String.t,
    :last_updated => DateTime.t,
    :userId => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.AnchoreImage do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:annotations, :struct, AnchoreEngineAPIServer.Model.Object, options)
    |> deserialize(:image_content, :struct, AnchoreEngineAPIServer.Model.ImageContent, options)
    |> deserialize(:image_detail, :list, AnchoreEngineAPIServer.Model.ImageDetail, options)
  end
end

