# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.ApiErrorResponse do
  @moduledoc """
  Generic HTTP API error response
  """

  @derive [Poison.Encoder]
  defstruct [
    :code,
    :detail,
    :error_type,
    :message
  ]

  @type t :: %__MODULE__{
    :code => integer(),
    :detail => Object,
    :error_type => String.t,
    :message => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.ApiErrorResponse do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:detail, :struct, AnchoreEngineAPIServer.Model.Object, options)
  end
end

