# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.ArchivedAnalysis do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :analyzed_at,
    :annotations,
    :archive_size_bytes,
    :created_at,
    :imageDigest,
    :image_detail,
    :last_updated,
    :parentDigest,
    :status
  ]

  @type t :: %__MODULE__{
    :analyzed_at => DateTime.t,
    :annotations => Object,
    :archive_size_bytes => integer(),
    :created_at => DateTime.t,
    :imageDigest => String.t,
    :image_detail => [TagEntry],
    :last_updated => DateTime.t,
    :parentDigest => String.t,
    :status => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.ArchivedAnalysis do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:annotations, :struct, AnchoreEngineAPIServer.Model.Object, options)
    |> deserialize(:image_detail, :list, AnchoreEngineAPIServer.Model.TagEntry, options)
  end
end

