# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.ContentPackageResponseContent do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :license,
    :licenses,
    :location,
    :origin,
    :package,
    :size,
    :type,
    :version
  ]

  @type t :: %__MODULE__{
    :license => String.t,
    :licenses => [String.t],
    :location => String.t,
    :origin => String.t,
    :package => String.t,
    :size => String.t,
    :type => String.t,
    :version => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.ContentPackageResponseContent do
  def decode(value, _options) do
    value
  end
end

