# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.ContentFilesResponseContent do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :filename,
    :gid,
    :linkdest,
    :mode,
    :sha256,
    :size,
    :type,
    :uid
  ]

  @type t :: %__MODULE__{
    :filename => String.t,
    :gid => integer(),
    :linkdest => String.t,
    :mode => String.t,
    :sha256 => String.t,
    :size => integer(),
    :type => String.t,
    :uid => integer()
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.ContentFilesResponseContent do
  def decode(value, _options) do
    value
  end
end

