# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.ContentJavaPackageResponseContent do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :"implementation-version",
    :location,
    :"maven-version",
    :origin,
    :package,
    :"specification-version",
    :type
  ]

  @type t :: %__MODULE__{
    :"implementation-version" => String.t,
    :location => String.t,
    :"maven-version" => String.t,
    :origin => String.t,
    :package => String.t,
    :"specification-version" => String.t,
    :type => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.ContentJavaPackageResponseContent do
  def decode(value, _options) do
    value
  end
end

