# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.DeleteImageResponse do
  @moduledoc """
  Image deletion response containing status and details
  """

  @derive [Poison.Encoder]
  defstruct [
    :detail,
    :digest,
    :status
  ]

  @type t :: %__MODULE__{
    :detail => String.t,
    :digest => String.t,
    :status => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.DeleteImageResponse do
  def decode(value, _options) do
    value
  end
end

