# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.EventResponseEventResource do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :type,
    :user_id
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :type => String.t,
    :user_id => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.EventResponseEventResource do
  def decode(value, _options) do
    value
  end
end

