# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.EventCategory do
  @moduledoc """
  A collection of event subcategories
  """

  @derive [Poison.Encoder]
  defstruct [
    :category,
    :description,
    :subcategories
  ]

  @type t :: %__MODULE__{
    :category => String.t,
    :description => String.t,
    :subcategories => [EventSubcategory]
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.EventCategory do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:subcategories, :list, AnchoreEngineAPIServer.Model.EventSubcategory, options)
  end
end

