# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.EventDescription do
  @moduledoc """
  A description of an event type
  """

  @derive [Poison.Encoder]
  defstruct [
    :message,
    :name,
    :resource_type,
    :type
  ]

  @type t :: %__MODULE__{
    :message => String.t,
    :name => String.t,
    :resource_type => String.t,
    :type => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.EventDescription do
  def decode(value, _options) do
    value
  end
end

