# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.EventSubcategory do
  @moduledoc """
  A collection of events related to each other
  """

  @derive [Poison.Encoder]
  defstruct [
    :description,
    :events,
    :name
  ]

  @type t :: %__MODULE__{
    :description => String.t,
    :events => [EventDescription],
    :name => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.EventSubcategory do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:events, :list, AnchoreEngineAPIServer.Model.EventDescription, options)
  end
end

