# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.EventResponseEventSource do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :base_url,
    :hostid,
    :request_id,
    :servicename
  ]

  @type t :: %__MODULE__{
    :base_url => String.t,
    :hostid => String.t,
    :request_id => String.t,
    :servicename => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.EventResponseEventSource do
  def decode(value, _options) do
    value
  end
end

