# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.FeedGroupMetadata do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :created_at,
    :last_sync,
    :name,
    :record_count
  ]

  @type t :: %__MODULE__{
    :created_at => DateTime.t,
    :last_sync => DateTime.t,
    :name => String.t,
    :record_count => integer()
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.FeedGroupMetadata do
  def decode(value, _options) do
    value
  end
end

