# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.FeedMetadata do
  @moduledoc """
  Metadata on a single feed based on what the engine finds from querying the endpoints
  """

  @derive [Poison.Encoder]
  defstruct [
    :created_at,
    :groups,
    :last_full_sync,
    :name,
    :updated_at
  ]

  @type t :: %__MODULE__{
    :created_at => DateTime.t,
    :groups => [FeedGroupMetadata],
    :last_full_sync => DateTime.t,
    :name => String.t,
    :updated_at => DateTime.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.FeedMetadata do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:groups, :list, AnchoreEngineAPIServer.Model.FeedGroupMetadata, options)
  end
end

