# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.ImageDetail do
  @moduledoc """
  A metadata detail record for a specific image. Multiple detail records may map a single catalog image.
  """

  @derive [Poison.Encoder]
  defstruct [
    :created_at,
    :dockerfile,
    :fulldigest,
    :fulltag,
    :imageDigest,
    :imageId,
    :last_updated,
    :registry,
    :repo,
    :userId
  ]

  @type t :: %__MODULE__{
    :created_at => DateTime.t,
    :dockerfile => String.t,
    :fulldigest => String.t,
    :fulltag => String.t,
    :imageDigest => String.t,
    :imageId => String.t,
    :last_updated => DateTime.t,
    :registry => String.t,
    :repo => String.t,
    :userId => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.ImageDetail do
  def decode(value, _options) do
    value
  end
end

