# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.ImageFilter do
  @moduledoc """
  Filter for an image list by id, tag, or digest, but not both
  """

  @derive [Poison.Encoder]
  defstruct [
    :digest,
    :tag
  ]

  @type t :: %__MODULE__{
    :digest => String.t,
    :tag => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.ImageFilter do
  def decode(value, _options) do
    value
  end
end

