# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.ImageReference do
  @moduledoc """
  A summary of an image identity, including digest, id (if available), and any tags known to have ever been mapped to the digest
  """

  @derive [Poison.Encoder]
  defstruct [
    :analyzed_at,
    :digest,
    :id,
    :tag_history
  ]

  @type t :: %__MODULE__{
    :analyzed_at => String.t,
    :digest => String.t,
    :id => String.t,
    :tag_history => [TagEntry]
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.ImageReference do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:tag_history, :list, AnchoreEngineAPIServer.Model.TagEntry, options)
  end
end

