# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.ImageSelectionRule do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :image,
    :name,
    :registry,
    :repository
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :image => ImageRef,
    :name => String.t,
    :registry => String.t,
    :repository => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.ImageSelectionRule do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:image, :struct, AnchoreEngineAPIServer.Model.ImageRef, options)
  end
end

