# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.ImageWithPackages do
  @moduledoc """
  An image record that contains packages
  """

  @derive [Poison.Encoder]
  defstruct [
    :image,
    :packages
  ]

  @type t :: %__MODULE__{
    :image => ImageReference,
    :packages => [PackageReference]
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.ImageWithPackages do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:image, :struct, AnchoreEngineAPIServer.Model.ImageReference, options)
    |> deserialize(:packages, :list, AnchoreEngineAPIServer.Model.PackageReference, options)
  end
end

