# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.ImageAnalysisRequest do
  @moduledoc """
  A request to add an image to be watched and analyzed by the engine. Optionally include the dockerfile content. Either source, digest or tag must be present.
  """

  @derive [Poison.Encoder]
  defstruct [
    :annotations,
    :created_at,
    :digest,
    :dockerfile,
    :image_type,
    :source,
    :tag
  ]

  @type t :: %__MODULE__{
    :annotations => Object,
    :created_at => DateTime.t,
    :digest => String.t,
    :dockerfile => String.t,
    :image_type => String.t,
    :source => ImageSource,
    :tag => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.ImageAnalysisRequest do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:annotations, :struct, AnchoreEngineAPIServer.Model.Object, options)
    |> deserialize(:source, :struct, AnchoreEngineAPIServer.Model.ImageSource, options)
  end
end

