# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.ImageSelector do
  @moduledoc """
  A set of selection criteria to match an image by a tagged pullstring based on its components, with regex support in each field
  """

  @derive [Poison.Encoder]
  defstruct [
    :registry,
    :repository,
    :tag
  ]

  @type t :: %__MODULE__{
    :registry => String.t,
    :repository => String.t,
    :tag => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.ImageSelector do
  def decode(value, _options) do
    value
  end
end

