# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.ImageRef do
  @moduledoc """
  A reference to an image
  """

  @derive [Poison.Encoder]
  defstruct [
    :type,
    :value
  ]

  @type t :: %__MODULE__{
    :type => Object,
    :value => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.ImageRef do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:type, :struct, AnchoreEngineAPIServer.Model.Object, options)
  end
end

