# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.MappingRule do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :image,
    :name,
    :policy_id,
    :policy_ids,
    :registry,
    :repository,
    :whitelist_ids
  ]

  @type t :: %__MODULE__{
    :id => String.t,
    :image => ImageRef,
    :name => String.t,
    :policy_id => String.t,
    :policy_ids => [String.t],
    :registry => String.t,
    :repository => String.t,
    :whitelist_ids => [String.t]
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.MappingRule do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:image, :struct, AnchoreEngineAPIServer.Model.ImageRef, options)
  end
end

