# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.MetadataResponse do
  @moduledoc """
  Generic wrapper for metadata listings from images
  """

  @derive [Poison.Encoder]
  defstruct [
    :imageDigest,
    :metadata,
    :metadata_type
  ]

  @type t :: %__MODULE__{
    :imageDigest => String.t,
    :metadata => Object,
    :metadata_type => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.MetadataResponse do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:metadata, :struct, AnchoreEngineAPIServer.Model.Object, options)
  end
end

