# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.NvdDataObject do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :cvss_v2,
    :cvss_v3,
    :id
  ]

  @type t :: %__MODULE__{
    :cvss_v2 => Cvssv2Scores,
    :cvss_v3 => Cvssv3Scores,
    :id => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.NvdDataObject do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:cvss_v2, :struct, AnchoreEngineAPIServer.Model.Cvssv2Scores, options)
    |> deserialize(:cvss_v3, :struct, AnchoreEngineAPIServer.Model.Cvssv3Scores, options)
  end
end

