# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.PaginatedVulnerableImageList do
  @moduledoc """
  Pagination wrapped list of images with vulnerabilties that match some filter
  """

  @derive [Poison.Encoder]
  defstruct [
    :next_page,
    :page,
    :returned_count,
    :images
  ]

  @type t :: %__MODULE__{
    :next_page => String.t,
    :page => String.t,
    :returned_count => integer(),
    :images => [VulnerableImage]
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.PaginatedVulnerableImageList do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:images, :list, AnchoreEngineAPIServer.Model.VulnerableImage, options)
  end
end

