# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.PaginationProperties do
  @moduledoc """
  Properties for common pagination handling to be included in any wrapping object that needs pagination elements
  """

  @derive [Poison.Encoder]
  defstruct [
    :next_page,
    :page,
    :returned_count
  ]

  @type t :: %__MODULE__{
    :next_page => String.t,
    :page => String.t,
    :returned_count => integer()
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.PaginationProperties do
  def decode(value, _options) do
    value
  end
end

