# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.PolicyBundleRecord do
  @moduledoc """
  A policy bundle plus some metadata
  """

  @derive [Poison.Encoder]
  defstruct [
    :active,
    :created_at,
    :last_updated,
    :policyId,
    :policy_source,
    :policybundle,
    :userId
  ]

  @type t :: %__MODULE__{
    :active => boolean(),
    :created_at => DateTime.t,
    :last_updated => DateTime.t,
    :policyId => String.t,
    :policy_source => String.t,
    :policybundle => PolicyBundle,
    :userId => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.PolicyBundleRecord do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:policybundle, :struct, AnchoreEngineAPIServer.Model.PolicyBundle, options)
  end
end

