# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.PolicyRule do
  @moduledoc """
  A rule that defines and decision value if the match is found true for a given image.
  """

  @derive [Poison.Encoder]
  defstruct [
    :action,
    :gate,
    :id,
    :params,
    :trigger
  ]

  @type t :: %__MODULE__{
    :action => Object,
    :gate => String.t,
    :id => String.t,
    :params => [PolicyRuleParams],
    :trigger => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.PolicyRule do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:action, :struct, AnchoreEngineAPIServer.Model.Object, options)
    |> deserialize(:params, :list, AnchoreEngineAPIServer.Model.PolicyRuleParams, options)
  end
end

