# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.PolicyBundle do
  @moduledoc """
  A bundle containing a set of policies, whitelists, and rules for mapping them to specific images
  """

  @derive [Poison.Encoder]
  defstruct [
    :blacklisted_images,
    :comment,
    :id,
    :mappings,
    :name,
    :policies,
    :version,
    :whitelisted_images,
    :whitelists
  ]

  @type t :: %__MODULE__{
    :blacklisted_images => [ImageSelectionRule],
    :comment => String.t,
    :id => String.t,
    :mappings => [MappingRule],
    :name => String.t,
    :policies => [Policy],
    :version => String.t,
    :whitelisted_images => [ImageSelectionRule],
    :whitelists => [Whitelist]
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.PolicyBundle do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:blacklisted_images, :list, AnchoreEngineAPIServer.Model.ImageSelectionRule, options)
    |> deserialize(:mappings, :list, AnchoreEngineAPIServer.Model.MappingRule, options)
    |> deserialize(:policies, :list, AnchoreEngineAPIServer.Model.Policy, options)
    |> deserialize(:whitelisted_images, :list, AnchoreEngineAPIServer.Model.ImageSelectionRule, options)
    |> deserialize(:whitelists, :list, AnchoreEngineAPIServer.Model.Whitelist, options)
  end
end

