# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.Policy do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :comment,
    :id,
    :name,
    :rules,
    :version
  ]

  @type t :: %__MODULE__{
    :comment => String.t,
    :id => String.t,
    :name => String.t,
    :rules => [PolicyRule],
    :version => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.Policy do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:rules, :list, AnchoreEngineAPIServer.Model.PolicyRule, options)
  end
end

