# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.RegexContentMatch do
  @moduledoc """
  Match of a named regex on a file
  """

  @derive [Poison.Encoder]
  defstruct [
    :lines,
    :name,
    :regex
  ]

  @type t :: %__MODULE__{
    :lines => [integer()],
    :name => String.t,
    :regex => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.RegexContentMatch do
  def decode(value, _options) do
    value
  end
end

