# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.RegistryConfiguration do
  @moduledoc """
  A registry entry describing the endpoint and credentials for a registry to pull images from
  """

  @derive [Poison.Encoder]
  defstruct [
    :created_at,
    :last_upated,
    :registry,
    :registry_name,
    :registry_type,
    :registry_user,
    :registry_verify,
    :userId
  ]

  @type t :: %__MODULE__{
    :created_at => DateTime.t,
    :last_upated => DateTime.t,
    :registry => String.t,
    :registry_name => String.t,
    :registry_type => String.t,
    :registry_user => String.t,
    :registry_verify => boolean(),
    :userId => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.RegistryConfiguration do
  def decode(value, _options) do
    value
  end
end

