# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.RetrievedFile do
  @moduledoc """
  The retrieved file entry including content (b64 encoded)
  """

  @derive [Poison.Encoder]
  defstruct [
    :b64_content,
    :path
  ]

  @type t :: %__MODULE__{
    :b64_content => String.t,
    :path => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.RetrievedFile do
  def decode(value, _options) do
    value
  end
end

