# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.Service do
  @moduledoc """
  A service status record
  """

  @derive [Poison.Encoder]
  defstruct [
    :base_url,
    :hostid,
    :service_detail,
    :servicename,
    :status,
    :status_message,
    :version
  ]

  @type t :: %__MODULE__{
    :base_url => String.t,
    :hostid => String.t,
    :service_detail => StatusResponse,
    :servicename => String.t,
    :status => boolean(),
    :status_message => String.t,
    :version => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.Service do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:service_detail, :struct, AnchoreEngineAPIServer.Model.StatusResponse, options)
  end
end

