# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.ServiceVersion do
  @moduledoc """
  Version information for a service
  """

  @derive [Poison.Encoder]
  defstruct [
    :api,
    :db,
    :service
  ]

  @type t :: %__MODULE__{
    :api => ServiceVersionApi,
    :db => ServiceVersionDb,
    :service => ServiceVersionService
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.ServiceVersion do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:api, :struct, AnchoreEngineAPIServer.Model.ServiceVersionApi, options)
    |> deserialize(:db, :struct, AnchoreEngineAPIServer.Model.ServiceVersionDb, options)
    |> deserialize(:service, :struct, AnchoreEngineAPIServer.Model.ServiceVersionService, options)
  end
end

