# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.ServiceVersionDb do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :schema_version
  ]

  @type t :: %__MODULE__{
    :schema_version => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.ServiceVersionDb do
  def decode(value, _options) do
    value
  end
end

