# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.StatusResponse do
  @moduledoc """
  System status response
  """

  @derive [Poison.Encoder]
  defstruct [
    :available,
    :busy,
    :db_version,
    :detail,
    :message,
    :up,
    :version
  ]

  @type t :: %__MODULE__{
    :available => boolean(),
    :busy => boolean(),
    :db_version => String.t,
    :detail => Object,
    :message => String.t,
    :up => boolean(),
    :version => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.StatusResponse do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:detail, :struct, AnchoreEngineAPIServer.Model.Object, options)
  end
end

