# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.Subscription do
  @moduledoc """
  Subscription entry
  """

  @derive [Poison.Encoder]
  defstruct [
    :active,
    :subscription_id,
    :subscription_key,
    :subscription_type,
    :subscription_value,
    :userId
  ]

  @type t :: %__MODULE__{
    :active => boolean(),
    :subscription_id => String.t,
    :subscription_key => String.t,
    :subscription_type => String.t,
    :subscription_value => String.t,
    :userId => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.Subscription do
  def decode(value, _options) do
    value
  end
end

