# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.SubscriptionRequest do
  @moduledoc """
  A subscription entry to add to the system
  """

  @derive [Poison.Encoder]
  defstruct [
    :subscription_key,
    :subscription_type,
    :subscription_value
  ]

  @type t :: %__MODULE__{
    :subscription_key => String.t,
    :subscription_type => String.t,
    :subscription_value => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.SubscriptionRequest do
  def decode(value, _options) do
    value
  end
end

