# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.SystemStatusResponse do
  @moduledoc """
  System status response
  """

  @derive [Poison.Encoder]
  defstruct [
    :service_states
  ]

  @type t :: %__MODULE__{
    :service_states => ServiceList
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.SystemStatusResponse do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:service_states, :struct, AnchoreEngineAPIServer.Model.ServiceList, options)
  end
end

