# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.TagEntry do
  @moduledoc """
  A docker-pullable tag value as well as deconstructed components
  """

  @derive [Poison.Encoder]
  defstruct [
    :detected_at,
    :pullstring,
    :registry,
    :repository,
    :tag
  ]

  @type t :: %__MODULE__{
    :detected_at => DateTime.t,
    :pullstring => String.t,
    :registry => String.t,
    :repository => String.t,
    :tag => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.TagEntry do
  def decode(value, _options) do
    value
  end
end

