# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.TriggerSpec do
  @moduledoc """
  Definition of a trigger and its parameters
  """

  @derive [Poison.Encoder]
  defstruct [
    :description,
    :name,
    :parameters,
    :state,
    :superceded_by
  ]

  @type t :: %__MODULE__{
    :description => String.t,
    :name => String.t,
    :parameters => [TriggerParamSpec],
    :state => String.t,
    :superceded_by => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.TriggerSpec do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:parameters, :list, AnchoreEngineAPIServer.Model.TriggerParamSpec, options)
  end
end

