# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.User do
  @moduledoc """
  A username for authenticating with one or more types of credentials. User type defines the expected credentials allowed for the user. Native users have passwords, External users have no credential internally. Internal users are service/system users for inter-service communication.
  """

  @derive [Poison.Encoder]
  defstruct [
    :created_at,
    :last_updated,
    :source,
    :type,
    :username
  ]

  @type t :: %__MODULE__{
    :created_at => DateTime.t,
    :last_updated => DateTime.t,
    :source => String.t,
    :type => String.t,
    :username => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.User do
  def decode(value, _options) do
    value
  end
end

