# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.UserCreationRequest do
  @moduledoc """
  A payload for creating a new user, includes the username and password in a single request
  """

  @derive [Poison.Encoder]
  defstruct [
    :password,
    :username
  ]

  @type t :: %__MODULE__{
    :password => String.t,
    :username => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.UserCreationRequest do
  def decode(value, _options) do
    value
  end
end

