# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.VulnerableImage do
  @moduledoc """
  A record of an image vulnerable to some known vulnerability. Includes vulnerable package information
  """

  @derive [Poison.Encoder]
  defstruct [
    :affected_packages,
    :image
  ]

  @type t :: %__MODULE__{
    :affected_packages => [VulnerablePackageReference],
    :image => ImageReference
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.VulnerableImage do
  import AnchoreEngineAPIServer.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:affected_packages, :list, AnchoreEngineAPIServer.Model.VulnerablePackageReference, options)
    |> deserialize(:image, :struct, AnchoreEngineAPIServer.Model.ImageReference, options)
  end
end

