# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.VulnerablePackageReference do
  @moduledoc """
  A record of a software item which is vulnerable or carries a fix for a vulnerability
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :namespace,
    :severity,
    :type,
    :version
  ]

  @type t :: %__MODULE__{
    :name => String.t,
    :namespace => String.t,
    :severity => String.t,
    :type => String.t,
    :version => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.VulnerablePackageReference do
  def decode(value, _options) do
    value
  end
end

