# NOTE: This class is auto generated by the swagger code generator program.
# https://github.com/swagger-api/swagger-codegen.git
# Do not edit the class manually.

defmodule AnchoreEngineAPIServer.Model.WhitelistItem do
  @moduledoc """
  Identifies a specific gate and trigger match from a policy against an image and indicates it should be ignored in final policy decisions
  """

  @derive [Poison.Encoder]
  defstruct [
    :gate,
    :id,
    :trigger_id
  ]

  @type t :: %__MODULE__{
    :gate => String.t,
    :id => String.t,
    :trigger_id => String.t
  }
end

defimpl Poison.Decoder, for: AnchoreEngineAPIServer.Model.WhitelistItem do
  def decode(value, _options) do
    value
  end
end

